import { useCallback, useEffect, useMemo, useState } from "react";
import { getDarkVessels, getIncidentFull, getIncidents, getReferenceLayers, getVessels } from "./api/gateway";
import { IncidentFeed } from "./components/IncidentFeed";
import { IntelligencePanel } from "./components/IntelligencePanel";
import { RecommendationPanel } from "./components/RecommendationPanel";
import { VesselPanel } from "./components/VesselPanel";
import { useLiveUpdates } from "./hooks/useLiveUpdates";
import { OperationalMap } from "./map/OperationalMap";
import type { DarkVessel, IncidentDetail, IncidentSummary, ProtectedArea, Vessel } from "./types";
import { ago, selectedForecast, severity } from "./utils/format";

const horizons = [0, 6, 12, 24, 48, 72];
const initialLayers = { vessels: true, spill: true, dark: true, zones: true, forecast: true, coastline: false };

export default function App() {
  const [incidents, setIncidents] = useState<IncidentSummary[]>([]); const [vessels, setVessels] = useState<Vessel[]>([]); const [darkVessels, setDarkVessels] = useState<DarkVessel[]>([]); const [areas, setAreas] = useState<ProtectedArea[]>([]);
  const [activeId, setActiveId] = useState<string | undefined>(); const [detail, setDetail] = useState<IncidentDetail | null>(null); const [selectedVessel, setSelectedVessel] = useState<Vessel | null>(null); const [horizon, setHorizon] = useState(0); const [layers, setLayers] = useState(initialLayers);
  const [loading, setLoading] = useState({ incidents: true, detail: false }); const [error, setError] = useState<string | null>(null); const [lastUpdate, setLastUpdate] = useState<Date | null>(null);
  const refreshOverview = useCallback(async () => { const settled = await Promise.allSettled([getIncidents(), getVessels(), getDarkVessels(), getReferenceLayers()]); const [i, v, d, a] = settled; if (i.status === "fulfilled") { setIncidents(i.value.incidents || []); setActiveId(id => id || i.value.incidents?.[0]?.id); } else setError("BACKEND CONNECTION LOST: incident feed unavailable."); if (v.status === "fulfilled") setVessels(v.value.vessels || []); if (d.status === "fulfilled") setDarkVessels(d.value.dark_vessels || []); if (a.status === "fulfilled") setAreas(a.value.protected_areas || []); setLastUpdate(new Date()); setLoading(current => ({ ...current, incidents: false })); }, []);
  const refreshDetail = useCallback(async (id = activeId) => { if (!id) return; setLoading(current => ({ ...current, detail: true })); try { const next = await getIncidentFull(id); setDetail(next); setHorizon(current => selectedForecast(next.forecasts, current) ? current : 0); setError(null); } catch { setDetail(null); setError("Unable to load incident intelligence."); } finally { setLoading(current => ({ ...current, detail: false })); } }, [activeId]);
  useEffect(() => { void refreshOverview(); const timer = setInterval(() => void refreshOverview(), 60000); return () => clearInterval(timer); }, [refreshOverview]);
  useEffect(() => { void refreshDetail(); }, [activeId, refreshDetail]);
  const onLiveEvent = useCallback((event: any) => { if (["incident_fused", "spill_attributed", "spill_severity", "spill_response"].includes(event.type)) { void refreshOverview(); if (activeId) void refreshDetail(activeId); } if (event.type === "ais" || event.type === "risk") void refreshOverview(); if (event.type === "dark_vessel") void getDarkVessels().then(r => setDarkVessels(r.dark_vessels || [])).catch(() => {}); setLastUpdate(new Date()); }, [activeId, refreshDetail, refreshOverview]);
  const connection = useLiveUpdates(onLiveEvent);
  const critical = useMemo(() => incidents.filter(i => severity(i.severity_level) === "CRITICAL").length, [incidents]);
  const availableHorizons = useMemo(() => new Set(detail?.forecasts.map(item => Number(item.horizon_hours)) || []), [detail]);
  const selectIncident = (id: string) => { setActiveId(id); setSelectedVessel(null); };
  const onVesselClick = useCallback((mmsi: string) => setSelectedVessel(vessels.find(v => v.mmsi === mmsi) || null), [vessels]);
  const fitAll = () => { const first = incidents[0]; if (first) setActiveId(first.id); };
  return <main className="command-shell"><header><div className="brand"><span className="emblem">◈</span><div><strong>AUTHORITY COMMAND CENTER</strong><small>MARITIME OIL-SPILL INTELLIGENCE</small></div></div><div className={`connection ${connection}`}><i />{connection === "live" ? "LIVE" : connection === "connecting" ? "CONNECTING" : "DISCONNECTED"}</div><div className="header-stats"><span>ACTIVE INCIDENTS <b>{incidents.length.toString().padStart(2, "0")}</b></span><span>CRITICAL <b className="critical-text">{critical.toString().padStart(2, "0")}</b></span><span>UPDATED <b>{lastUpdate ? ago(lastUpdate.toISOString()) : "—"}</b></span></div></header>{error && <div className="connection-alert">{error}</div>}<div className="workspace"><aside className="left-column"><IntelligencePanel detail={detail} loading={loading.detail} /><RecommendationPanel recommendations={detail?.recommendations || []} onChanged={() => void refreshDetail()} /><IncidentFeed incidents={incidents} selectedId={activeId} loading={loading.incidents} onSelect={selectIncident} /></aside><section className="map-region"><div className="map-heading"><div><span>OPERATIONAL MARITIME PICTURE</span><strong>{detail ? `INCIDENT ${detail.incident.id.slice(0, 8).toUpperCase()}` : "AWAITING INCIDENT"}</strong></div><button onClick={fitAll}>LOCATE INCIDENT</button></div><OperationalMap detail={detail} vessels={vessels} darkVessels={darkVessels} areas={areas} layers={layers} horizon={horizon} onVesselClick={onVesselClick} /><div className="layer-control"><span>MAP LAYERS</span>{([ ["vessels", "Vessels"], ["spill", "Spill"], ["dark", "Dark vessels"], ["zones", "Risk zones"], ["forecast", "Forecast"], ["coastline", "Coastline"] ] as [keyof typeof layers, string][]).map(([key, label]) => <label key={key}><input type="checkbox" checked={layers[key]} onChange={() => setLayers(current => ({ ...current, [key]: !current[key] }))} />{label}</label>)}</div><div className="timeline"><span>FORECAST</span>{horizons.map(value => <button key={value} disabled={value !== 0 && !availableHorizons.has(value)} className={horizon === value ? "selected" : ""} onClick={() => setHorizon(value)}>{value === 0 ? "NOW" : `+${value}H`}</button>)}<em>{horizon === 0 ? "Current spill" : availableHorizons.has(horizon) ? `Forecast +${horizon}H` : "Unavailable"}</em></div><VesselPanel vessel={selectedVessel} onClose={() => setSelectedVessel(null)} /></section></div></main>;
}
